spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"
    # this specifies the import from configserver
    # it made optional because, if it fails to load still the app should work


  datasource:
    url: jdbc:mysql://localhost:3306/eduser
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Jithin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#server:
#  port: 8082
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#jwt:
#  secret: supersecret
#
#app:
#  client:
#    url: http://localhost:4200