spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8088"

  datasource:
    url: jdbc:mysql://localhost:3306/eduCrafterUser
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Jithin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update