spring:
  application:
    name: academics-service
  config:
    import: "optional:configserver:http://localhost:8088"
    # this specifies the import from configserver
    # it made optional because, if it fails to load still the app should work


#  datasource:
#    url: jdbc:mysql://localhost:3306/edacademics
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Jithin123
  datasource:
    url: jdbc:mysql://34.93.111.216:3306/edacademics
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ~T$+8Hf"1<IU9EGA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
