server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
      # we are adding this to publish 100% logs to zipkin

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
