server:
  port: 8084
  rabbitmq:
    addresses : localhost:5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
      # we are adding this to publish 100% logs to zipkin

#Email integration config
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jithinsp4@gmail.com
    password: oqcwsgdphfzuycyd
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true